# Generated by Django 3.1.1 on 2020-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_modified",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="document",
            name="last_modified",
            field=models.DateField(auto_now=True),
        ),
    ]
