# Generated by Django 3.1.1 on 2020-12-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_auto_20201224_2159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email_address",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
