# Generated by Django 3.1.1 on 2020-12-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_auto_20201224_2201"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
    ]
