# Generated by Django 3.1.1 on 2020-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_remove_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.FileField(default="temp", upload_to="temps/"),
            preserve_default=False,
        ),
    ]
