# Generated by Django 3.1.1 on 2020-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_auto_20201227_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_hash",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
