# Generated by Django 3.1.1 on 2020-12-29 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_customer_email_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email_address",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email_hash",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=254,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
